### ISSUE TITLE
character '\xfc' Error on Windows

### ISSUE THREAD

**Issue by 1271** [yuru-yuri/Manga-Downloader#6]
Traceback (most recent call last):
  File "manga.py", line 404, in <module>
    main(url, name)
  File "manga.py", line 384, in main
    manga.download_images()
  File "manga.py", line 337, in download_images
    print('Start downloading %s' % (archive_name, ))
  File "C:\Python35\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xfc' in position 46: character maps to <undefined>

**Comment by 1271** [comment]
SEE https://github.com/yuru-yuri/Manga-Downloader/commit/74169e8907c0d61e5fc24a13fe11c0f3095dc8fd
